### ISSUE TITLE
rename master banch to main

### ISSUE THREAD

**Issue by fedhere** [LSST-TVSSC/LSST-TVSSC.github.io#31]
in order to avoid historically charged wording GitHub as moved to rename its "master" branch default (reminiscent of master-slave) to "main". Please consider renaming the branch

**Comment by rachel3834** [comment]
Here are some instructions on how to do this:
https://www.git-tower.com/learn/git/faq/git-rename-master-to-main

I'd be very happy to have this updated to main.  The procedure requires that everyone who is committing to the repo to update their local copy of it, so when this goes ahead, the repo owners (presumably now Igor and Sara?) would need to notify everyone.  

Assigning this to Igor in the first instance to draw attention to this issue; please feel free to reassign to whomever is most appropriate.
