### ISSUE TITLE
How to update email addresses?

### ISSUE THREAD

**Issue by MelissaGraham** [LSST-TVSSC/LSST-TVSSC.github.io#5]
I found that for two of the Supernova subgroup members, their emails in our database have expired. I want to replace them with newer email addresses, but can't figure out in which file this information is kept. Can someone help me out with this?

**Comment by fedhere** [comment]
on our own DB? that is a google spreadsheet. I think onlyl Rachel and I
have editing rights tho cause subgroup leads... come and go. Can you send
me the addresses and I will update them?

F

___________________________________________________
federica b. bianco
*http://fbb.space/ <http://fbb.space/>*
____________________________________________________


                                     -                         _`
                                   `+*-                       ;*;
                                  `o**=                  `   :**o.
                     `.~.`        ;*ooo`                ~~  .o*oo=
                    `-----~       =oio*                ~--` :ooo**.^`
 `
      ;`            .------`      :oee;               `---^ :e*i!?oi^
+_  -io**=
      $$i.        `.:;_---`   ~`  `+=_                `---` .*ee?!i+
i: -eo*oe;       .~^
      $OOOe_      -__++_-`   ^-.   ^ ``                .~_:_.-*!!e*~
~_~i?eo*o~      `---^
      $OOOOO?;`   -----^     `-^  ^__:-`       ^~      ~;.    .*ee:
-. -!?eo**       ^----
      $OOOOOOO$i. `~-^        ^.^`^--_^        _-    ^=- `~:;;+++^  --
  _!?***:        --~`
      :_;o?OOOOO$*-      `_:-~^    ``     ~.  ~:-   ;o.:+:~`~i+++_;_
  .ie**+
           ^;!OOOOO!_   :i^               i:  --` ^*e+:.=       ~o`
^::``.`
              .=%OOOO?_o:                 ;. `..~i$o_^..^+`
`;++++___.
                 _eOOOOo^               .:ie%?!e?*_;+_oo=^__.        ^
-i*o_  `
                   ~o$OO$*:..-^  .-::=e$$!=-`    `io**eo*:  ^`
~;:~*oii~ ~::~
                     ^?OOOOOOOO%$OOOO%o:^    +_  :*o*e*o*+    `.:-
:=+~.::. `++++.
                      `;i$O?%O%=io*e?$%e=~   oo^ +*oo*oo*;
.io*i^^_--`    ^++++_     ^-~
                         _; `=Oi`     `~;o!=^~=^ _**ooo**_    ~*ioo=
^.^      ;+++_     ---`
                              ;%%-         ~o=`  `oeoo:.;~     i*oii^
       `:++-     .--
                                +$~          ..   ;*e;          _iii:
         `.~      .^
                          ~--.  ^;%=~_;++++:`     ^*_
                         ~+:--``-`^;o!*+-  `:;`    `
             `.
                        `;++_-. ^    `.-_+:~  _;~
             --^
                        ^:++_-^     ^-;_    ..``~-.
             -_-.
                        `_;;-~      .-_-       ^---``
              __--
                         --_~       `--`       ^--;_-~
              ----^
                         .-^          .         ~_+_--^
              ----
                          `                      -;---.
              ^--^
                                                 `_---~
               .`
                                                  ^---.
          ``
                                                   `~-`
         `++.
                                                     .
         ^++_   -~

          ~:-   ~~

            `

             ^.

             ^_.

              --~

              ~-^

              `^

Please consider the environment before printing this e-mail

**Comment by rachel3834** [comment]
I'm checking through to make sure all updates to the website are made.  Is this update complete?  If so, can we close this issue?  If not, please send me the updates for the spreadsheet and I will make them.

**Comment by fedhere** [comment]
not sure, @MelissaGraham ?

**Comment by MelissaGraham** [comment]
Whoops sorry @fedhere, I never sent which email addresses need to be updated.

c.inserra@soton.ac.uk --> InserraC@cardiff.ac.uk
dr477@cam.ac.uk --> drothchild@berkeley.edu

Then we can close, @rachel3834

**Comment by rachel3834** [comment]
Thanks
